name: soepenpatatten
favicon: null
layout_spectrum: 0.3859860978554934
typography_spectrum: 0.06694419588893652
title: 'Soep & patatten'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.30786227225326
  lightness: 0.5687191477045417
  saturation: 0.12964602070860565
  rhythmicContrast: 0.046021773712709546
purpose: []
